### PR TITLE
Fixes for Flutter 3.22 compatibility

### PR DESCRIPTION
**Pull request by fareesh**
- `TextTheme` changes
- `intl` version bump
- `flutter_localizations` dependency

### CODE REVIEW

**Comment by yelkamel** [comment]
this need to be merged.

**Comment by ducnguyenenterprise** [comment]
Checked ! Thanks for contribution 👌

**Comment by bkleineibst** [comment]
Can you please release a new version with this PR.

**Comment by mattalbr** [comment]
Bump! @ducnguyenenterprise is it possible to release a new version with this PR?

**Comment by ducnguyenenterprise** [comment]
As mentioned in open [issue](https://github.com/smaho-engineering/weekday_selector/issues/13) here, when waiting for @vincevargadev  to release a new version, you can folk and use the last merged commit

**Comment by mattalbr** [comment]
> As mentioned in open [issue](https://github.com/smaho-engineering/weekday_selector/issues/13) here, when waiting for @vincevargadev to release a new version, you can folk and use the last merged commit

Got it, thank you! Sorry, I thought you had permissions to release a new version :)

**Comment by guplem** [comment]
A more straightforward way is to set this commit as the version as follows in your pubspec.yaml:
```yaml
  weekday_selector: # Temporary solution awaiting the release of a new version including the following PR: https://github.com/smaho-engineering/weekday_selector/pull/12
    git:
      url: https://github.com/smaho-engineering/weekday_selector.git
      ref: e9c604a8cabb04ea3a169c3379c270c59810e4b0
```

**Pull request merged**
